
import java.util.Scanner;


public class Main_1_giris {

    public static void AAmain(String[] args) {
/*
        int a = 30 / 0;
        System.out.println("naber gardas");
*/
 


        
/*        
        int[] a = {25, 30, 35, 40};
        System.out.println(a[5]);
*/
  


        
/*        
        try {
            int a = 10 / 0;                                           // ArithmeticException
        } catch (ArithmeticException x) {                             // Exception da yazabiliriz
            System.out.println("bir sayi 0 a bolunemez");
        }
*/
      



        
/*        
        try {
            int[] a = {5, 10, 15, 20};
            System.out.println(a[5]);
        } catch (ArrayIndexOutOfBoundsException x) {
        }
        System.out.println("arrayin boyunu astiniz.");            // try a yazdıgımız sey sorun cikartmazsa catch de calismaz7
                                                                  // exception handling yaptigimizda sorun olusmaz ve sistem patlamadan kodlari calistirmaya devam eder.
*/





/*
        try{
        
        int[] a = {10,20,30};
        System.out.println(a[5]);
        }
        
        catch(RuntimeException x){                                // hatanin adini veriyor cok islevsel
        x.printStackTrace();
        }
*/





/*    
    try{
        int b = 5 / 0;
        
    int[] a = {10,20,30};
    System.out.println(a[5]);
    
    
    
    }
    
    catch(ArithmeticException e){
    System.out.println("sayi 0 a bolunemez.");
    }
    
    catch(ArrayIndexOutOfBoundsException a){
      System.out.println("arrayin boyunu astiniz.");  
    }
    
    catch(RuntimeException x){                                  
    System.out.println("bir hata olustu");
    x.printStackTrace();
    }
*/
        









    System.out.println("SELAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMİN ALEYKUM");
    }
}
